version: "3.9"

services:
  app1:
    build: .
    environment:
      - APP_NAME=app1
  app2:
    build: .
    environment:
      - APP_NAME=app2
  app3:
    build: .
    environment:
      - APP_NAME=app3
  nginx:
    build: ./nginx
    container_name: nginx_server
    ports:
      - "443:443"
    depends_on:
      - app1
      - app2
      - app3
